install.packages("dplyr")
library(dplyr)
sessionInfo()
mtcars
mtcars %>% head()
dim()
also : dim()
mtcars %>% dim()
mtcars %>% nrow()
mtcars %>% ncol()
mtcars %>% names()
mtcars %>% class()
mtcars %>% summary()
iris %>% summary()
library(dplyr)
iris %>% glimpse()
filter(iris, Species == "Setosa")
iris2 %>% dim()
iris2 <- iris %>% filter(Species == "Setosa")
iris %>% dim()
iris2 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 2)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5.2)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5.4)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 5.6)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length > 6)
iris3 %>% dim()
iris %>% filter(Sepal.Length > 5) %>% dim()
history
history(100)

